### ISSUE TITLE
管理科学专业简介

### ISSUE THREAD

**Issue by Guo-Zhang** [quanttide/quanttide-tutorial-of-readme#1]

**Comment by DaylilyLuo** [comment]
(对清华管科硕士四个问题回答的整理）
管科未来就业方向：
本科毕业：广泛商科方向皆可。
研究生：热门方向包括数据分析、泛商科、金融、咨询，也可考虑公务员。

想更靠近计算机方向的准备：
考研：了解计算机硕士方向，学习相关内容。
就业：按计算机本科课程学习核心课程，重点学习Python、R语言和SQL。
实习：强调实习经验，不推荐过多参与比赛，建议找到自己感兴趣的赛道。

电商的就业方向：
自选路线：电商和泛商科方向都是自选的，取决于实习路径选择。
主要方向：电商领域包括管培、销售运营、数据分析等。

对商科知识没兴趣：
学好当前专业，建议找兴趣相符的专业，可在大一刷分后转专业。

**Comment by DaylilyLuo** [comment]
补：
本科学习经验分享：
计量和CS需自己补充，特别是stats的hypothesis testing，需要学明白。
建议国内教学水平不高时上什么课都没用，容易毁掉对课程的兴趣。

出国留学建议：
找便宜的出国机会，公立学校老师水平可能不错但在国内不出名。
Master两年好好学习，最好有一些项目经验。
PhD可能需要补充统计、计量和CS算法，强导师制，产出要求高，也有偏向health data的方向。
ps国外读master的实例：本科管科/国际贸易，去了CMU的MIS（主要是高强度的编程和刷题课，可做DS或去小公司）。

我们教育战略：
目标是用一个开源+商业化的体系填补国内教育缺失的空白。
大一的同学还有机会，可以多实习，扩展项目经验。

**Comment by DaylilyLuo** [comment]
管理科学内容（待审）

学习内容建议
本科阶段：
管理类数学：高等代数、线性代数、计量经济学是基础；数学要求相对工科低。
泛商科方向：适合本科毕业生，包括但不限于商业分析、数据分析、金融、咨询行业。
数据分析类：强调学习数据分析，掌握 Python、R、SQL 等工具。
计量和CS补充：特别强调学习统计学中的假设检验（hypothesis testing），需要深入理解。
ps对商科知识没兴趣：学好当前专业，建议找兴趣相符的专业，可在大一刷分后转专业。
研究生阶段：
数据分析：深入学习与商业分析相关的数据科学技能。
泛商科方向：选择与商业相关的专业，如银行、券商、咨询。
公务员考试：对于研究生来说，考公务员需要注意选择与管理科学相关的专业。

跨考选择建议
考研跨考：
兴趣文科：新闻学、行政管理。
偏商科：海外商科专业、自动化等。
考虑计算机方向：产品经理、商业分析。
*针对计算机硕士考研：根据考研要求学习相关内容。
（ps实习经验比参加比赛更重要，推荐多参与实习。
避免过度参与比赛，实习经历更有利于找到自己感兴趣的领域。）

学习经验分享及出国留学建议
计量和CS：自己补充，尤其是统计学中的假设检验。
选课建议：在国内教学水平相对较低时，选择课程时需谨慎，避免毁掉对课程的兴趣。
出国留学：找经济实惠的机会，公立学校可能教学水平不错。
Master阶段：好好学习，争取积累项目经验。
PhD阶段：可能需要补充统计学、计量经济学和CS算法，注重导师制和高产出要求。

就业方向
技术岗位：产品经理等，强调商业方向，不要过于偏向技术。
电商领域：包括管培、销售运营、数据分析等。
文科生：考虑兴趣，可能选择偏文科的经管专业，如会计或财务。
实习路径选择：先规划好职业发展方向，再选择实习路径。

我们的教育战略
目标：填补国内教育缺失的空白，采用开源和商业化的体系。
对大一同学的建议：有机会的话，多参与实习，扩展项目经验。

**Comment by JASON8219** [comment]
框架很完整 可以在某个部分加一句推介我们的教程，考虑在学习内容建议或我们的教育战略部分

**Comment by DaylilyLuo** [comment]
我们的教育战略
综合管理科学和技术培训：
为团队成员提供系统的管理科学培训，强调数据工程、信息系统设计和维护的理论与实践。
整合计算机科学和管理学的知识，使团队成员能够理解并解决数据处理流程中的管理问题。
跨学科合作：
促进计算机科学专业和管理科学专业之间的跨学科合作，以建立更全面的专业素养。
在团队中鼓励成员分享知识，促进技术和管理的相互学习。
项目实践和创新：
鼓励团队成员积极参与实际项目，特别是具有数据工程和信息系统设计背景的项目。
提供资源支持，帮助团队成员自主组建项目，解决实际管理挑战。
专业素质提升：
针对计算机专业成员，提供经管知识培训，加强团队的综合素质。
针对经管专业成员，提供计算机知识培训，使其具备解决技术问题的能力。
导师制度和团队合作：
建立导师制度，由具有丰富经验的导师指导团队成员，传授实际项目经验。
促进团队内外的合作，与其他团队或企业建立合作关系，分享经验和资源。
创赛项目支持：
提供支持，鼓励团队参与创赛项目，尤其是与数据工程相关的比赛。
提供资源和指导，帮助团队在项目中解决复杂的数据处理流程中遇到的管理问题。
具体实施：
课程设计和培训计划：
制定专门的培训计划，涵盖计算机软件和管理科学的核心概念。
设计跨学科课程，以培养团队成员对数据工程和信息系统管理的全面理解。
公众号和知识分享：
利用公众号“量潮科技”等平台，分享团队在数据工程领域的经验和成果。
激励团队成员积极参与社会化媒体，扩大团队的影响力和专业知名度。

**Comment by DaylilyLuo** [comment]
> 框架很完整 可以在某个部分加一句推介我们的教程，考虑在学习内容建议或我们的教育战略部分

**“课程设计和培训计划：
制定专门的培训计划，涵盖计算机软件和管理科学的核心概念。
设计跨学科课程，以培养团队成员对数据工程和信息系统管理的全面理解。”**这样写可以吗

**Comment by DaylilyLuo** [comment]
学习内容建议
本科阶段：
管理类数学：高等代数、线性代数、计量经济学是基础；数学要求相对工科低。
泛商科方向：适合本科毕业生，包括但不限于商业分析、数据分析、金融、咨询行业。
数据分析类：强调学习数据分析，掌握 Python、R、SQL 等工具。
计量和CS补充：特别强调学习统计学中的假设检验（hypothesis testing），需要深入理解。
ps对商科知识没兴趣：学好当前专业，建议找兴趣相符的专业，可在大一刷分后转专业。
研究生阶段：
数据分析：深入学习与商业分析相关的数据科学技能。
泛商科方向：选择与商业相关的专业，如银行、券商、咨询。
公务员考试：对于研究生来说，考公务员需要注意选择与管理科学相关的专业。

跨考选择建议
考研跨考：
兴趣文科：新闻学、行政管理。
偏商科：海外商科专业、自动化等。
考虑计算机方向：产品经理、商业分析。
*针对计算机硕士考研：根据考研要求学习相关内容。
（ps实习经验比参加比赛更重要，推荐多参与实习。
避免过度参与比赛，实习经历更有利于找到自己感兴趣的领域。）

学习经验分享及出国留学建议
计量和CS：自己补充，尤其是统计学中的假设检验。
选课建议：在国内教学水平相对较低时，选择课程时需谨慎，避免毁掉对课程的兴趣。
出国留学：找经济实惠的机会，公立学校可能教学水平不错。
Master阶段：好好学习，争取积累项目经验。
PhD阶段：可能需要补充统计学、计量经济学和CS算法，注重导师制和高产出要求。

就业方向
技术岗位：产品经理等，强调商业方向，不要过于偏向技术。
电商领域：包括管培、销售运营、数据分析等。
文科生：考虑兴趣，可能选择偏文科的经管专业，如会计或财务。
实习路径选择：先规划好职业发展方向，再选择实习路径。

我们的教育战略
专业素质提升和技术培训：
为团队成员提供系统的管理科学培训，强调数据工程、信息系统设计和维护的理论与实践。
整合计算机科学和管理学的知识，使团队成员能够理解并解决数据处理流程中的管理问题。
导师制度和团队合作：
建立导师制度，由具有丰富经验的导师指导团队成员，传授实际项目经验。
促进团队内外的合作，与其他团队或企业建立合作关系，分享经验和资源。
项目实践和创新：
鼓励团队成员积极参与实际项目，特别是具有数据工程和信息系统设计背景的项目。
提供资源支持，帮助团队成员自主组建项目，解决实际管理挑战。
创赛项目支持：
提供支持，鼓励团队参与创赛项目，尤其是与数据工程相关的比赛。
提供资源和指导，帮助团队在项目中解决复杂的数据处理流程中遇到的管理问题。
具体实施：
课程设计和培训计划：
制定专门的培训计划，涵盖计算机软件和管理科学的核心概念。
设计跨学科课程，以培养团队成员对数据工程和信息系统管理的全面理解。

我们这里有个创赛项目，在做一个数据工程的信息系统，主要用来解决复杂的数据处理流程中遇到的管理问题。想了解可以在公众号“量潮科技”找到相关文章。

**Comment by DaylilyLuo** [comment]
已pr到管理学教程
